#:import C kivy.utils.get_color_from_hex

<MainLayout>:
    orientation: 'vertical'
    size: root.width, root.height
    MDBoxLayout:
        size_hint_y: None
        height: 104
        canvas.before:
            Color:
                rgba: C('#BAD7E9')
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: 'Checkout Counter Software'
            font_size: 45
            text_color: C('#2B3467')
        
    MDBoxLayout:
        orientation: 'horizontal'
        MDBoxLayout:
            orientation: 'vertical'
            size_hint_x: None
            width: 320
            canvas.before:
                Color:
                    rgba: C('#BAD7E9')
                Rectangle:
                    pos: self.pos
                    size: self.size
            
            MDRaisedButton:
                text: "Inventory"
                on_press: scrn_mngr.show_inventory_screen()
                group: 'screen'
            MDRaisedButton:
                text: "Transaction"
                on_press: scrn_mngr.show_transaction_screen()
                group: 'screen'
            MDRaisedButton:
                text: "Report"
                on_press: scrn_mngr.show_report_screen()
                group: 'screen'
            MDRaisedButton:
                text: "Employee"
                on_press: scrn_mngr.show_employee_screen()
                group: 'screen'
            Label:
                text: ''
        ScreenLayout:
            id: scrn_mngr
            orientation: 'vertical'     
<TextInput>:
    size_hint: (None, None)
    size: (300, 50)

<UpdateItemScreen>:
    MDBoxLayout:
        size_hint: (1, 1)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: C('#ffffff')
            Rectangle:
                pos: self.pos
                size: self.size

        GridLayout:
            cols: 2
            rows: 4
            size_hint: (0.8, 0.4)
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            Label:
                text: 'Category'
                font_size: 22
                color: C('#2B3467')
            TextInput:
                id: product_category
                hint_text: 'Product Category'
            Label:
                text: 'Product Name'
                font_size: 22
                color: C('#2B3467')
            TextInput:
                id: product_name
                hint_text: 'Product Name'
            Label:
                text: 'Product Price'
                font_size: 22
                color: C('#2B3467')
            TextInput:
                id: product_price
                hint_text: 'Product Price'
            Label:
                text: 'Product Quantity'
                font_size: 22
                color: C('#2B3467')
            TextInput:
                id: product_quantity
                hint_text: 'Product Quantity'
            
            

            
