#:import C kivy.utils.get_color_from_hex

<LogInScreen>:
    id: login_scrn
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    
    BoxLayout:
        size: root.width, root.height
        orientation: 'vertical'
        size_hint: None, None

        Label:
            size: 1280, 104
            size_hint: None, None
            canvas.before:
                Color:
                    rgba: (0.7294117647058823, 0.8431372549019608, 0.9137254901960784, 1)
                Rectangle:
                    size: self.size
                    pos: self.pos
            text: 'Checkout Counter'
            text_size: 1280-31, self.height
            valign: 'center'
            halign: 'left'
            font_size: 45
            color: (43/255,52/255,103/255,1)
            font_family: 'Lexend'
        
        BoxLayout: 
            orientation: 'vertical'
            size: 1280, 187
            size_hint: None, None

            Label:
                text_size: self.size
                text: 'Login'
                font_size: 40
                text_size: self.size
                halign: 'center'
                color: (43/255,52/255,103/255,1)
                font_family: 'Lexend'

        BoxLayout: 
            orientation: 'vertical'
            size: 1280, 429

            Label: 
                text: ''
                size: 1280, 17
                size_hint: None, None

            BoxLayout:
                size: 386, 58
                size_hint: None, None
                pos_hint: {'center_x': 0.5}

                canvas.before:
                    Color:
                        rgba: 229/255, 229/255, 229/255, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [13]
                TextInput:
                    background_color: 229/255, 229/255, 229/255, 0
                    background_normal: ''
                    background_active: ''
                    size: 386, 58
                    size_hint: None, None
                    id: username_field
                    pos_hint: {'center_x': .5}
                    hint_text: 'Username'
                    hint_text_color: 0.7, 0.7, 0.7, 1
                    multiline: False
                    focus: True
                    on_text_validate: pwd_field.focus = True
                    font_family: "Lexend"

            Label: 
                text: ''
                size: 1280, 17
                size_hint: None, None

            BoxLayout:
                size: 386, 58
                size_hint: None, None
                pos_hint: {'center_x': 0.5}

                canvas.before:
                    Color:
                        rgba: 229/255, 229/255, 229/255, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius: [13]

                TextInput:
                    id: pwd_field
                    background_color: 229/255, 229/255, 229/255, 0
                    background_normal: ''
                    background_active: ''
                    size_hint: 1,1
                    hint_text: 'Password'
                    valign: 'center'
                    password: True
                    hint_text_color: 0.7, 0.7, 0.7, 1
                    multiline: False
                    focus: True
                    font_family: "Lexend"
                    on_text_validate: root.validate_user()

            Label:
                id: info
                text: ''
                color: (1,0,0,1)
                markup: True
                size: 1280, 33
                size_hint: None, None
                pos_hint: {'center_x': .5}
                font_size: 13

            Button: 
                pos_hint: {'center_x': .5}
                size: 160, 58
                size_hint: None, None
                text: 'Log in'
                on_release: root.validate_user()
                font_family: "Lexend"

            Label: 
                text: ''
                size: 1280, 100
                size_hint: None, None

            Label:
                size: 1280, 22
                size_hint: None, None
                pos_hint: {'right': 0.99}

<HomeScreenAdmin>:
    orientation: 'vertical'
    size: root.width, root.height
    MDBoxLayout:
        size_hint_y: None
        height: 104
        canvas.before:
            Color:
                rgba: C('#BAD7E9')
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: 'Checkout Counter Software'
            font_size: 45
            text_color: C('#2B3467')
        
    MDBoxLayout:
        orientation: 'horizontal'
        MDBoxLayout:
            orientation: 'vertical'
            size_hint_x: None
            width: 320
            canvas.before:
                Color:
                    rgba: C('#BAD7E9')
                Rectangle:
                    pos: self.pos
                    size: self.size
            
            MDRaisedButton:
                text: "Inventory"
                on_press: scrn_mngr.show_inventory_screen()
                group: 'screen'
            MDRaisedButton:
                text: "Transaction"
                on_press: scrn_mngr.show_transaction_screen()
                group: 'screen'
            MDRaisedButton:
                text: "Report"
                on_press: scrn_mngr.show_report_screen()
                group: 'screen'
            MDRaisedButton:
                text: "Employee"
                on_press: scrn_mngr.show_employee_screen()
                group: 'screen'
            Label:
                text: ''
        ScreenLayout:
            id: scrn_mngr
            orientation: 'vertical' 

<MainLayout>: